INSERT INTO exercises (id, name, muscular_group) VALUES
    (1, 'Supino Reto', 0),
    (2, 'Supino com Halteres', 0),
    (3, 'Crossover', 0),
    (4, 'Peck Deck', 0),
    (5, 'Remada com Halteres', 1),
    (6, 'Puxada Frontal', 1),
    (7, 'Remada Máquina', 1),
    (8, 'Pullover', 1),
    (9, 'Barra Fixa', 1),
    (10, 'Agachamento Livre', 2),
    (11, 'Leg Press', 2),
    (12, 'Cadeira Extensora', 2),
    (13, 'Cadeira Flexora', 2),
    (14, 'Gêmeos', 2),
    (15, 'Rosca com Halteres', 3),
    (16, 'Rosca Sentado', 3),
    (17, 'Rosca Scott', 3),
    (18, 'Rosca Martelo', 3),
    (19, 'Triceps Polia', 4),
    (20, 'Triceps Testa', 4),
    (21, 'Triceps Francês', 4),
    (22, 'Desenvolvimeno', 5),
    (23, 'Elevação Lateral', 5);
